name: 'f1_project'
version: '1.0.0'
config-version: 2

profile: 'f1_project'

model-paths: ["models"]
clean-targets: ["target", "dbt_modules"]

models:
  f1_project:
    mart:
      +schema: mart
      +materialized: table

    +meta:
      raw:
        +schema: raw
        +materialized: view
flags:
  require_generic_test_arguments_property: true