f1_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: plenti-project
      dataset: f1_raw_data
      threads: 4
      keyfile: ~/.gcp/f1-gcp-service-account.json
      location: US
