f1_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: plenti-project
      dataset: f1_analytics
      location: US
      threads: 4
      timeout_seconds: 300